### ISSUE TITLE
--allstats not working

### ISSUE THREAD

**Issue by VinceG90** [JonathanReeve/macro-etym#27]
The --allstats command does not appear to be working. The output when using that command along with a text is just "Other Languages." Otherwise, appears to be working fine.

**Comment by JonathanReeve** [comment]
Right you are. Looks like pycountry.languages changed their API. Serves me right for not specifying version numbers in setup.py. Let me know if it works now. (You might have to uninstall the old verion and reinstall the newest version straight from GitHub for it to work.) 

Also, if you end up doing something interesting with this, especially if it's something with literary analysis, let me know!

**Comment by VinceG90** [comment]
Thanks for the quick response! It seems to work just fine, thanks so much.

I am working on an analysis of Tolkien's work, more specifically, how Tolkien achieves a feeling of myth and deep time though the use of language. Basically, I want to find a way to stress-test, if not push back on the idea that Tolkien creates the mythical "feel" of his fiction by privileging Germanic (read: pre-Norman Invasion) English vocabulary. So far, the stats from Macroetym seem to suggest Tolkien does not necessarily privilege non-Latinate English vocabulary more than coeval British authors, but I thought having more granular data would be helpful. That's why the --allstats command seemed important to my purposes. Anyway, this project is still very much in the early stages, so I'd love to keep you posted if I come end up with some useful findings. 

Thanks so much for all your work on this tool!

**Comment by JonathanReeve** [comment]
That's a really interesting study. And exactly the kind of thing I was hoping people would do with macro-etym! Definitely sent me a link to the paper if you write something about it. 

Also, you're probably already doing something like this, but if you're looking for a more granular, chapter-level analysis, and want an easy way to break up a plain text file into its chapters, in order to run `macroetym` over all the chapters comparatively, you can use [chapterize](https://github.com/JonathanReeve/chapterize), and then just feed all the filenames as a single wildcard expression to macroetym: `macroetym --allstats tolkien_chapters/*.txt`. I find that if you're familiar with the text, you'll see interesting etymological variations on the chapter or chapter section level (like in [my analysis of the _Canterbury Tales_](http://jonreeve.com/2017/06/macro-etymological-canterbury-tales/)).
