### ISSUE TITLE
0.0% results for all attempted text files

### ISSUE THREAD

**Issue by mg608** [JonathanReeve/macro-etym#31]
Hello, 
I have tried running your tool on a series of txt files, however each file always returns 0.0% results for each language (Austronesian, Balto-Slavic etc.).

I'm not receiving any errors but I can't figure out how to get a percentage breakdown for any text. Do you have any suggestions for where to look to resolve this?

Attached a sample text file that I've been using:
[Ulysses Corpus II.txt](https://github.com/JonathanReeve/macro-etym/files/8694821/Ulysses.Corpus.II.txt)

**Comment by JonathanReeve** [comment]
I looked into this, and it turns out to be a file encoding issue. `macro-etym` was trying to read your file as utf-8, but it failed, since it's utf-16. But rather than throw an error, it just kept on going as usual, because I set it up to ignore errors. [I've rewritten the file handler](https://github.com/JonathanReeve/macro-etym/commit/1704a69801d9f5773bd27594c78976f376ab34f5), so it should be fixed now. Try it again with the latest version (`git pull` etc), and let me know if that fixes it. 

Fixed in 1704a698
